server:
  port: 9090
spring:
  application:
    name: springboot-hello-world
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
